# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dcorT_test_Rcpp <- function(x, y) {
    .Call(`_corrp_dcorT_test_Rcpp`, x, y)
}

