# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acca_main <- function(m, k, maxrep = 2L, maxiter = 100L) {
    .Call('_corrp_acca_main', PACKAGE = 'corrp', m, k, maxrep, maxiter)
}

silhouette_main <- function(acca, m) {
    .Call('_corrp_silhouette_main', PACKAGE = 'corrp', acca, m)
}

