# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csample_char <- function(x, size, replace, prob = as.numeric( c())) {
    .Call('_corrp_csample_char', PACKAGE = 'corrp', x, size, replace, prob)
}

randcluster <- function(m, k) {
    .Call('_corrp_randcluster', PACKAGE = 'corrp', m, k)
}

which_in <- function(x, y) {
    .Call('_corrp_which_in', PACKAGE = 'corrp', x, y)
}

